### ISSUE TITLE
payload can not be null error after install with OpenLDAP

### ISSUE THREAD

**Issue by nthisler** [pwm-project/pwm#188] opened 2017-06-19 15:01 UTC
The first time after install when I tried logging in I got this as the 500 error...the logs say:

**Logs:**
2017-06-19T14:55:39Z, WARN , ldap.LdapOperationsHelper, unable to resolve GUID value for user UserIdentity{"userDN":"cn=test-user,ou=users,dc=example,dc=com","ldapProfile":"default"}
2017-06-19T14:55:39Z, ERROR, value.PwmValueTag, error executing value tag option 'clientETag', error: payload can not be null
2017-06-19T14:55:39Z, WARN , ldap.LdapOperationsHelper, unable to resolve GUID value for user UserIdentity{"userDN":"cn=test-user,ou=users,dc=example,dc=com","ldapProfile":"default"}

**Tomcat:**

type Exception report

message java.lang.NullPointerException: payload can not be null

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: java.lang.NullPointerException: payload can not be null
	password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:124)
	password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:74)
	password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	password.pwm.http.filter.ObsoleteUrlFilter.processFilter(ObsoleteUrlFilter.java:50)
	password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	password.pwm.http.filter.RequestInitializationFilter.initializeServletRequest(RequestInitializationFilter.java:210)
	password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:129)
	password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:73)
root cause

java.lang.NullPointerException: payload can not be null
	password.pwm.svc.cache.CacheService.put(CacheService.java:116)
	password.pwm.ldap.LdapOperationsHelper.readLdapGuidValue(LdapOperationsHelper.java:204)
	password.pwm.ldap.UserInfoReader.getUserGuid(UserInfoReader.java:461)
	sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	password.pwm.util.java.CachingProxyWrapper.lambda$create$0(CachingProxyWrapper.java:65)
	com.sun.proxy.$Proxy53.getUserGuid(Unknown Source)
	password.pwm.http.filter.AuthenticationFilter.handleAuthenticationCookie(AuthenticationFilter.java:212)
	password.pwm.http.filter.AuthenticationFilter.processAuthenticatedSession(AuthenticationFilter.java:177)
	password.pwm.http.filter.AuthenticationFilter.processFilter(AuthenticationFilter.java:119)
	password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:108)
	password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:74)
	password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	password.pwm.http.filter.ObsoleteUrlFilter.processFilter(ObsoleteUrlFilter.java:50)
	password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	password.pwm.http.filter.RequestInitializationFilter.initializeServletRequest(RequestInitializationFilter.java:210)
	password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:129)
	password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:73)

**Comment by pvagner** [comment] 2017-07-08 11:07
I'm also getting this. I am using openldap, I have included the openldap.schema in my config. I have just passed configuration guide. I am getting this after an initial login. Is this a pwm issue or am I missing some data in my ldap directory?

**Comment by pvagner** [comment] 2017-07-08 12:40
Possible workaround suggestion is in this thread. I am not building this my-self so I can't verify atm.... https://groups.google.com/forum/#!topic/pwm-general/W6d0P7IciZE

**Comment by seba81** [comment] 2017-08-02 19:45
Same issue here. Anyone maked it working?

**Comment by pvagner** [comment] 2017-08-02 19:48
I've disabled the cache and rebuilt the app from sources as suggested in the discussion thread I've linked in my previous comment. It's working for me with these tweaks.

**Comment by seba81** [comment] 2017-08-03 13:08
thank you pvagner. I'll try that.

**Comment by jrivard** [comment] 2017-09-18 18:23
this should be fixed in current builds...

**Comment by toanc** [comment] 2017-09-19 05:40
@jrivard  Are you sure? I just tried the latest version 

`pwm-1.8.0-SNAPSHOT-2017-09-13T17-23-36Z-release-bundle.zip but`

But seems it still there 

Otherwise, where can I get 1.7 build so far ?

**Comment by jrivard** [comment] 2017-09-19 06:27
Please provide exact steps to reproduce.

**Comment by jrivard** [comment] 2017-09-19 06:29
Oh, actually this is an OpenLDAP issue...  As I have asked for info on how OpenLDAP handles entry guids and no one has answered on the forum or here, I can't fix it.

**Comment by toanc** [comment] 2017-09-19 06:32
This is the first time I heard about GUID. Not sure what exactly you talking about but I assume this one https://msdn.microsoft.com/en-us/library/ms677985(v=vs.85).aspx ?

**Comment by toanc** [comment] 2017-09-19 06:35
if it was related to BIND method so my concern is Why don't we use the BIND mechanism as usual. Why do we have to use Object UID for binding

**Comment by asacamano** [comment] 2017-11-02 00:56
@jrivard I think this might be what is needed. I've included the setting file format, since that is easiest for people to use, but I'm working on a pull request to include it in the schema.

    <setting key="ldap.guidAttribute" syntax="STRING" profile="default" syntaxVersion="0" modifyTime="2017-10-25T02:09:28Z">
      <label>LDAP GUID Attribute</label>
      <value><![CDATA[entryuuid]]></value>
    </setting>

See also https://github.com/pwm-project/pwm/pull/234

**Comment by jrivard** [comment] 2017-11-09 07:31
the above has since been added via pull request, closing this issue.

**Closed by jrivard** 2017-11-09 07:31 UTC
