### ISSUE TITLE
Error installing on Websphere Liberty Profile Server

### ISSUE THREAD

**Issue by arejay73** [pwm-project/pwm#27] opened 2015-12-22 16:19 UTC
------Start of DE processing------ = [12/22/15 11:14:32:915 EST]
Exception = java.lang.NullPointerException
Source = com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters
probeid = 1105
Stack Dump = java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3035)
	at java.net.URI.<init>(URI.java:607)
	at password.pwm.util.PwmServletURLHelper.checkIfStartsWithURL(PwmServletURLHelper.java:97)
	at password.pwm.util.PwmServletURLHelper.isPrivateUrl(PwmServletURLHelper.java:52)
	at password.pwm.util.ServletHelper.handleRequestInitialization(ServletHelper.java:509)
	at password.pwm.SessionFilter.processFilter(SessionFilter.java:105)
	at password.pwm.SessionFilter.doFilter(SessionFilter.java:90)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at password.pwm.GZIPFilter.doFilter(GZIPFilter.java:45)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1020)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1142)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4867)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:297)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:997)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:262)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:955)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:341)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:470)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:404)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:284)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:255)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1017)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:626)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1766)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:929)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:809)

**Comment by jrivard** [comment] 2016-01-19 18:42
We don't test or design for containers other than tomcat, so this won't be fixed unless code is supplied to fix it by someone who has tested it, and it doesn't break tomcat support.

**Closed by jrivard** 2016-01-19 18:42 UTC

**Comment by hajk1** [comment] 2016-03-14 14:33
I know the issue is closed but I had the same problem with some thing else and I have added the solution [here](http://stackoverflow.com/questions/35868621/ibm-websphere-8-5-5-8liberty-spring-security-3-1-3-release/35990270#35990270).
May be it helps some body.
