### ISSUE TITLE
Help Error: Error 5015 Self Service Password PWM

### ISSUE THREAD

**Issue by krijoma85** [pwm-project/pwm#576] opened 2020-10-21 16:47 UTC
Hi!

I have installed in the company a Free Software called: Self Service PWM, for the password reset by the user.
Currently I have an error when trying to configure the sending of emails:

This is the error I get on screen:

Error 5015
An error has occurred. If this error occurs repeatedly please contact your help desk.

5015 INTERNAL_ERROR (unexpected error during action handler for ‘password.pwm.http.servlet.configeditor.ConfigEditorServlet:emailHealthCheck’, error: null)
Checking the logs I find this:

2020-10-06T17:02:18Z, INFO , pwm.PwmApplication, initializing, application mode=NEW, applicationPath=/opt/pwm, configFile=null
2020-10-06T17:02:18Z, WARN , logging.PwmLogManager, unable to initialize localDBLogger: localDB can not be null
2020-10-06T17:02:18Z, ERROR, pwm.PwmApplication, error retrieving key ‘context_instanceID’, localDB unavailable:
2020-10-06T17:02:18Z, INFO , pwm.PwmApplication, generated new random instanceID F14FBABE0A51AA47
2020-10-06T17:02:18Z, ERROR, pwm.PwmApplication, error retrieving key ‘lastLdapError’, localDB unavailable:
2020-10-06T17:02:18Z, ERROR, stats.StatisticsManager, LocalDB is not available, will remain closed
2020-10-06T17:02:18Z, WARN , email.EmailService, localdb is not open, EmailService will remain closed

I would appreciate it if someone else has done this, please let me know how it works out.

Thank you very much.

**Comment by markkrj** [comment] 2020-10-22 14:17
Duplicate of #575...
Email actually work, if you use SMTPS or Plain SMTP, as STARTLTLS has a bug (see #519 and #494). But the Health check does not. You can apply my patches mentioned in the issues and it will work.
PWM is the base for SSPR which is a paid product by Micro Focus, so they don't seem to care much about open source version. Actually, it seems that they have purpose bugs in PWM... They even changed the license for PWM to a permissive one, so they don't need to apply SSPR's PWM's fixes here...

**Comment by jrivard** [comment] 2021-08-05 22:07
Unable to reproduce as of v2.0.0, please re-open if this issue still exists.

**Closed by jrivard** 2021-08-05 22:07 UTC

**Comment by BloodyIron** [comment] 2022-12-20 06:17
CAN CONFIRM the E-Mail actually works it is the TEST E-Mail that fails. Using : fjudith/pwm:latest because it includes database plugins. That image is using 2.0.0-SNAPSHOT

Boy did I burn literal days trying to figure that one out...

**Comment by BloodyIron** [comment] 2022-12-20 06:18
Thanks to @markkrj for pointing out "it just works" despite test E-Mail not working, ARGH!
