### ISSUE TITLE
Group Membership still not working on login

### ISSUE THREAD

**Issue by holtzp** [pwm-project/pwm#588] opened 2021-01-20 01:56 UTC
PWM Version | v2.0.0-SNAPSHOT b99db009
Build Time | December 29, 2020, 5:48:28 PM CST

I'm seeing the exact same bug reported by someone else in Issue #581, which was closed as fixed in the latest build. It's not.

_After updating to the latest build, when I log in as an Administrator and Help Desk member, neither option show up on my "Authenticated Page" There is no Help Desk option nor the Administration option. If I go into the config and click "View Matches" the group members return for both Help Desk and Administrators groups._

If I replace the LDAP Group with an LDAP Search Filter that specifies the group, then it works.

Thanks!
Paul

**Comment by holtzp** [comment] 2021-01-20 07:25
Appears to be the same issue as #583 also.

Thanks!
Paul

**Comment by jrivard** [comment] 2021-06-15 07:17
Closing as duplicate of #583

**Closed by jrivard** 2021-06-15 07:17 UTC
