### ISSUE TITLE
Problem involving SMS : Peer not authenticated

### ISSUE THREAD

**Issue by Hippiefabou** [pwm-project/pwm#26] opened 2015-12-22 16:17 UTC
Hello everyone,

I have been trying to add a SMS option to reset password, but so far I am stuck on the following problem:
"ERROR, password.pwm.util.queue.SmsQueueManager, unexpected exception while sending SMS: peer not authenticated"

From what I have read so far, I realise this has to do with the SSL negociation not being successful, and should therefore import my SMS provider AC and/or certificate.

The piece of information I am missing is the following : where in the configuration do I find the path to the keystore used by PWM?
I have added the certificates to the keystore in the JRE_HOME, but nothing changed.

Thanks for your help,

**Comment by fwi27** [comment] 2016-01-08 22:57
This problem has be confirmed to be related to the lack of SNI support described here : https://github.com/pwm-project/pwm/issues/30

**Comment by jrivard** [comment] 2016-01-19 18:47
Closing issue since issue #30 is the root cause.

**Closed by jrivard** 2016-01-19 18:47 UTC
